### PR TITLE
Doc dockerfiles

### LINKED ISSUE #431: can there be a reference dockerfile responsible for the image  and the repo that contains it here, or for infosec reasons, would such a link better be added to Confluence somewhere?
can there be a reference dockerfile responsible for the image  and the repo that contains it here, or for infosec reasons, would such a link better be added to Confluence somewhere?

one way or another, what i'm missing here is why this comment is just saying "such an image exists" rather than "such an image exists, and this is where it came from."

_Originally posted by @ransomw1c in https://github.com/oneconcern/datamon/pull/428_

### PR DESCRIPTION
**Pull request by fredbi**
* fixes #431

NOTE to reviewers: please jump at commit https://github.com/oneconcern/datamon/pull/435/commits/ecef099224dc5c18f92176618166ddb88f7850b8 to see changes relative to #428 and friends which this PR is based upon

### CODE REVIEW

**Comment by kerneltime** [comment]
This needs rebasing. Will refrain from doing it online :-)

**Comment by fredbi** [comment]
yes sure. I need to fix the whitelisting thing first: this is causing a lot of CI failures

**Comment by fredbi** [comment]
Rebased to current master

**Comment by fredbi** [comment]
@ransomw1c thanks

**Pull request merged**
