### PR TITLE
refact(ci): revisited vm install, test coverage

### PR DESCRIPTION
**Pull request by fredbi**
**NOTE**: this bends on #381 

Generated artifacts are available at: https://app.circleci.com/jobs/github/oneconcern/datamon/5009/artifacts

# refact(ci): revisited vm install, test coverage

Our CI workflows have become complex over time. Time for refactoring a bit.

- machine executor install refactoring
   * refactored VM install to clarify the various steps (brew, fuse, golang)
   * revisited golang install on VM dedicated to fuse tests: picks latest release automatically

- other jobs factorized with commands
   * factorized go module cache handling as shorter commands
   * clarified credentials setup with an explicit command
   * removed redundant environment specs

- test coverage reporting
   * refactored test coverage collection and reporting as CI artifacts, using a trailer job to merge coverage metrics
   * kept the junit test report as test_result (visualization in circleci console)
   * produced coverage reports merging the results from all test jobs
   * produced summarized coverage report

Signed-off-by: Frederic BIDON <frederic@oneconcern.com>

### CODE REVIEW

**Comment by kerneltime** [comment]
```

github.com/oneconcern/datamon/cmd/datamon/cmd | 57.45% | 667/1161
-- | -- | --
github.com/oneconcern/datamon/pkg/auth/google | 58.33% | 14/24
github.com/oneconcern/datamon/pkg/cafs | 82.65% | 662/801
github.com/oneconcern/datamon/pkg/context | 2.78% | 1/36
github.com/oneconcern/datamon/pkg/core | 64.22% | 1217/1895
github.com/oneconcern/datamon/pkg/errors | 54.76% | 23/42
github.com/oneconcern/datamon/pkg/filetracker | 91.89% | 68/74
github.com/oneconcern/datamon/pkg/model | 40.11% | 71/177
github.com/oneconcern/datamon/pkg/sidecar/param | 24.93% | 93/373
github.com/oneconcern/datamon/pkg/storage/gcs | 66.22% | 98/148
github.com/oneconcern/datamon/pkg/storage/localfs | 56.96% | 45/79
github.com/oneconcern/datamon/pkg/storage/sthree | 78.21% | 61/78
github.com/oneconcern/datamon/pkg/wal | 84.14% | 122/145
github.com/oneconcern/datamon/pkg/web | 69.32% | 61/88
Report Total | 62.55% | 3203/5121

```

**Comment by kerneltime** [comment]
Best to let #381 in first?

**Comment by fredbi** [comment]
@kerneltime yes, we should merge #381 first. Besides, there is still a bug on coverage aggregation when different tags are used (btw this is really part of the go internals and everyone is subject to this, even if you are using somethnig like codecov). I'll try to address this during some spare cycles.

**Comment by fredbi** [comment]
@kerneltime I realize that there is no bug in coverage reports: actually, coverage is not registered when running a sub-process (well, this _should_ be possible to instrument a regular build with coverage, but this is not the case with standard build). Hence, we miss all the interesting parts covered by the workshop scenario (it is the same for the fuse cli).

Hence no bug, but a disappointment regarding the report, after much hard work on increasing test coverage...

**Pull request merged**
