### PR TITLE
experiment parallel testing with circleci

### PR DESCRIPTION
**Pull request by fredbi**
Signed-off-by: Frederic BIDON <frederic@oneconcern.com>

### CODE REVIEW

**Comment by fredbi** [comment]
@kerneltime here is an interesting failure that I often reproduce locally (without --race).
I am assuming there is some kind of race condition in the CLI tests, resulting in a deadlock.
https://circleci.com/gh/oneconcern/datamon/2294

**Comment by kerneltime** [comment]
Yes the CLI tests are dependent. They are closer to integration tests than unit tests, we can add build tag for them and run other tests in parallel?

**Comment by fredbi** [comment]
@kerneltime I'd be glad to parallelize this. Further, the fact that I am often running into issues locally may stem from non-deterministic scheduling of tests. If you could explain the dependency logic, we could secure the test suite, by wrapping all required steps as non-exported test funcs.

**Comment by fredbi** [comment]
@kerneltime I believe this is a lock between some tests running in `pkg` and some other running in `cmd`. Do we refer to the same buckets?

**Comment by kerneltime** [comment]
> @kerneltime I believe this is a lock between some tests running in `pkg` and some other running in `cmd`. Do we refer to the same buckets?

I don't think so, will look into this. There should not be any shared buckets between tests. I know the CLI tests have some sequence of operations it performs but it should be good to make them parallelized.

**Comment by fredbi** [comment]
stopping this line for the moment, trying new ideas following ransom's suggestions.

**Pull request closed without merging**
